"""add device binding fields to membership

Revision ID: d1cca7a30c41
Revises: f0b31cd61ff8
Create Date: 2026-08-12 02:17:37.420329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cca7a30c41'
down_revision: Union[str, None] = 'f0b31cd61ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('organization_memberships', sa.Column('device_flagged', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_memberships', 'device_flagged')
    op.drop_column('organization_memberships', 'device_id')
    # ### end Alembic commands ###
