"""add unique constraint to organization name

Revision ID: f0b31cd61ff8
Revises: c313c87e541a
Create Date: 2026-08-11 13:56:12.364853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b31cd61ff8'
down_revision: Union[str, None] = 'c313c87e541a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_organizations_name', 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organizations_name', 'organizations', type_='unique')
    # ### end Alembic commands ###
